source spSelectImages.sql;
source spSelectPosts.sql;
source spSelectUser.sql;
source spSelectAllImages.sql;
source spSelectTopImages.sql;
source spSelectNewImages.sql;
source spSelectAllContinents.sql;
source spSelectCountriesWithImages.sql;
source spSelectCitiesWithImages.sql;